<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJUjAwmK\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJUjAwmK/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJUjAwmK.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJUjAwmK\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJUjAwmK\App_KernelProdContainer([
    'container.build_hash' => 'JUjAwmK',
    'container.build_id' => 'd56842a2',
    'container.build_time' => 1619482557,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJUjAwmK');
