<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agenda extends \App\Entity\Agenda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'cuenta', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'campania', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'gestionar', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'agendador', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'nombreCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'emailCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'telefonoCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'ciudadCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'fechaCarga', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'fechaAsignado', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'sucursal', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'detalleCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'abogado', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'monto', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'usuarioUsuariocategorias', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'reunion', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'observacion', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'agendaObservacions', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'rutCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'telefonoRecadoCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'fechaContrato', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'contrato', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'lead', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'formId'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'cuenta', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'campania', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'gestionar', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'agendador', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'nombreCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'emailCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'telefonoCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'ciudadCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'fechaCarga', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'fechaAsignado', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'sucursal', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'detalleCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'abogado', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'monto', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'usuarioUsuariocategorias', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'reunion', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'observacion', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'agendaObservacions', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'rutCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'telefonoRecadoCliente', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'fechaContrato', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'contrato', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'lead', '' . "\0" . 'App\\Entity\\Agenda' . "\0" . 'formId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agenda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuenta(): ?\App\Entity\Cuenta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuenta', []);

        return parent::getCuenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuenta(?\App\Entity\Cuenta $cuenta): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuenta', [$cuenta]);

        return parent::setCuenta($cuenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampania(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampania', []);

        return parent::getCampania();
    }

    /**
     * {@inheritDoc}
     */
    public function setCampania(string $campania): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampania', [$campania]);

        return parent::setCampania($campania);
    }

    /**
     * {@inheritDoc}
     */
    public function getGestionar(): ?\App\Entity\Gestionar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGestionar', []);

        return parent::getGestionar();
    }

    /**
     * {@inheritDoc}
     */
    public function setGestionar(?\App\Entity\Gestionar $gestionar): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGestionar', [$gestionar]);

        return parent::setGestionar($gestionar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgendador(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgendador', []);

        return parent::getAgendador();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgendador(?\App\Entity\Usuario $agendador): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgendador', [$agendador]);

        return parent::setAgendador($agendador);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCliente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCliente', []);

        return parent::getNombreCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreCliente(?string $nombreCliente): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreCliente', [$nombreCliente]);

        return parent::setNombreCliente($nombreCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCliente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCliente', []);

        return parent::getEmailCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCliente(?string $emailCliente): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCliente', [$emailCliente]);

        return parent::setEmailCliente($emailCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoCliente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoCliente', []);

        return parent::getTelefonoCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoCliente(?string $telefonoCliente): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoCliente', [$telefonoCliente]);

        return parent::setTelefonoCliente($telefonoCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudadCliente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudadCliente', []);

        return parent::getCiudadCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudadCliente(?string $ciudadCliente): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudadCliente', [$ciudadCliente]);

        return parent::setCiudadCliente($ciudadCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCarga(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCarga', []);

        return parent::getFechaCarga();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCarga(?\DateTimeInterface $fechaCarga): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCarga', [$fechaCarga]);

        return parent::setFechaCarga($fechaCarga);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAsignado(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAsignado', []);

        return parent::getFechaAsignado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAsignado(?\DateTimeInterface $fechaAsignado): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAsignado', [$fechaAsignado]);

        return parent::setFechaAsignado($fechaAsignado);
    }

    /**
     * {@inheritDoc}
     */
    public function getSucursal(): ?\App\Entity\Sucursal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSucursal', []);

        return parent::getSucursal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSucursal(?\App\Entity\Sucursal $sucursal): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSucursal', [$sucursal]);

        return parent::setSucursal($sucursal);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?\App\Entity\AgendaStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?\App\Entity\AgendaStatus $status): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalleCliente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalleCliente', []);

        return parent::getDetalleCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalleCliente(?string $detalleCliente): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalleCliente', [$detalleCliente]);

        return parent::setDetalleCliente($detalleCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbogado(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbogado', []);

        return parent::getAbogado();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbogado(?\App\Entity\Usuario $abogado): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbogado', [$abogado]);

        return parent::setAbogado($abogado);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto(?string $monto): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioUsuariocategorias(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioUsuariocategorias', []);

        return parent::getUsuarioUsuariocategorias();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuarioUsuariocategoria(\App\Entity\UsuarioUsuariocategoria $usuarioUsuariocategoria): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuarioUsuariocategoria', [$usuarioUsuariocategoria]);

        return parent::addUsuarioUsuariocategoria($usuarioUsuariocategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuarioUsuariocategoria(\App\Entity\UsuarioUsuariocategoria $usuarioUsuariocategoria): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuarioUsuariocategoria', [$usuarioUsuariocategoria]);

        return parent::removeUsuarioUsuariocategoria($usuarioUsuariocategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getReunion(): ?\App\Entity\Reunion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReunion', []);

        return parent::getReunion();
    }

    /**
     * {@inheritDoc}
     */
    public function setReunion(?\App\Entity\Reunion $reunion): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReunion', [$reunion]);

        return parent::setReunion($reunion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion(?string $observacion): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgendaObservacions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgendaObservacions', []);

        return parent::getAgendaObservacions();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgendaObservacion(\App\Entity\AgendaObservacion $agendaObservacion): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgendaObservacion', [$agendaObservacion]);

        return parent::addAgendaObservacion($agendaObservacion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgendaObservacion(\App\Entity\AgendaObservacion $agendaObservacion): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgendaObservacion', [$agendaObservacion]);

        return parent::removeAgendaObservacion($agendaObservacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutCliente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutCliente', []);

        return parent::getRutCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutCliente(?string $rutCliente): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutCliente', [$rutCliente]);

        return parent::setRutCliente($rutCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoRecadoCliente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoRecadoCliente', []);

        return parent::getTelefonoRecadoCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoRecadoCliente(?string $telefonoRecadoCliente): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoRecadoCliente', [$telefonoRecadoCliente]);

        return parent::setTelefonoRecadoCliente($telefonoRecadoCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaContrato(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaContrato', []);

        return parent::getFechaContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaContrato(?\DateTimeInterface $fechaContrato): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaContrato', [$fechaContrato]);

        return parent::setFechaContrato($fechaContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrato(): ?\App\Entity\Contrato
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrato', []);

        return parent::getContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function getLead(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead', []);

        return parent::getLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setLead(?string $lead): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead', [$lead]);

        return parent::setLead($lead);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormId', []);

        return parent::getFormId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormId(?string $formId): \App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormId', [$formId]);

        return parent::setFormId($formId);
    }

}
