<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU5dxPfF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU5dxPfF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU5dxPfF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU5dxPfF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU5dxPfF\App_KernelDevDebugContainer([
    'container.build_hash' => 'U5dxPfF',
    'container.build_id' => '6dbda53c',
    'container.build_time' => 1637244165,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU5dxPfF');
