<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pago extends \App\Entity\Pago implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'pagoTipo', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'pagoCanal', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'monto', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'boleta', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'observacion', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaPago', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'horaPago', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaRegistro', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'usuarioRegistro', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'comprobante', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'pagoCuotas', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaIngreso', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'ncomprobante', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'cuentaCorriente', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'anulado', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'usuarioAnulacion', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaAnulacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'pagoTipo', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'pagoCanal', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'monto', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'boleta', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'observacion', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaPago', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'horaPago', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaRegistro', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'usuarioRegistro', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'comprobante', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'pagoCuotas', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaIngreso', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'ncomprobante', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'cuentaCorriente', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'anulado', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'usuarioAnulacion', '' . "\0" . 'App\\Entity\\Pago' . "\0" . 'fechaAnulacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pago $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoTipo(): ?\App\Entity\PagoTipo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoTipo', []);

        return parent::getPagoTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagoTipo(?\App\Entity\PagoTipo $pagoTipo): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagoTipo', [$pagoTipo]);

        return parent::setPagoTipo($pagoTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoCanal(): ?\App\Entity\PagoCanal
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoCanal', []);

        return parent::getPagoCanal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagoCanal(?\App\Entity\PagoCanal $pagoCanal): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagoCanal', [$pagoCanal]);

        return parent::setPagoCanal($pagoCanal);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto(int $monto): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoleta(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoleta', []);

        return parent::getBoleta();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoleta(?string $boleta): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoleta', [$boleta]);

        return parent::setBoleta($boleta);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion(?string $observacion): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPago(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPago', []);

        return parent::getFechaPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPago(\DateTimeInterface $fechaPago): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPago', [$fechaPago]);

        return parent::setFechaPago($fechaPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraPago(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraPago', []);

        return parent::getHoraPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraPago(\DateTimeInterface $horaPago): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraPago', [$horaPago]);

        return parent::setHoraPago($horaPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaRegistro(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaRegistro', []);

        return parent::getFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaRegistro(\DateTimeInterface $fechaRegistro): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaRegistro', [$fechaRegistro]);

        return parent::setFechaRegistro($fechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioRegistro(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioRegistro', []);

        return parent::getUsuarioRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioRegistro(?\App\Entity\Usuario $usuarioRegistro): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioRegistro', [$usuarioRegistro]);

        return parent::setUsuarioRegistro($usuarioRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getComprobante(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComprobante', []);

        return parent::getComprobante();
    }

    /**
     * {@inheritDoc}
     */
    public function setComprobante(string $comprobante): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComprobante', [$comprobante]);

        return parent::setComprobante($comprobante);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoCuotas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoCuotas', []);

        return parent::getPagoCuotas();
    }

    /**
     * {@inheritDoc}
     */
    public function addPagoCuota(\App\Entity\PagoCuotas $pagoCuota): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPagoCuota', [$pagoCuota]);

        return parent::addPagoCuota($pagoCuota);
    }

    /**
     * {@inheritDoc}
     */
    public function removePagoCuota(\App\Entity\PagoCuotas $pagoCuota): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePagoCuota', [$pagoCuota]);

        return parent::removePagoCuota($pagoCuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaIngreso(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaIngreso', []);

        return parent::getFechaIngreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaIngreso(?\DateTimeInterface $fechaIngreso): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaIngreso', [$fechaIngreso]);

        return parent::setFechaIngreso($fechaIngreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getNcomprobante(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNcomprobante', []);

        return parent::getNcomprobante();
    }

    /**
     * {@inheritDoc}
     */
    public function setNcomprobante(?string $ncomprobante): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNcomprobante', [$ncomprobante]);

        return parent::setNcomprobante($ncomprobante);
    }

    /**
     * {@inheritDoc}
     */
    public function getCuentaCorriente(): ?\App\Entity\CuentaCorriente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuentaCorriente', []);

        return parent::getCuentaCorriente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCuentaCorriente(?\App\Entity\CuentaCorriente $cuentaCorriente): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCuentaCorriente', [$cuentaCorriente]);

        return parent::setCuentaCorriente($cuentaCorriente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnulado(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnulado', []);

        return parent::getAnulado();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnulado(?bool $anulado): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnulado', [$anulado]);

        return parent::setAnulado($anulado);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioAnulacion(): ?\App\Entity\usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioAnulacion', []);

        return parent::getUsuarioAnulacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioAnulacion(?\App\Entity\usuario $usuarioAnulacion): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioAnulacion', [$usuarioAnulacion]);

        return parent::setUsuarioAnulacion($usuarioAnulacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAnulacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAnulacion', []);

        return parent::getFechaAnulacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAnulacion(?\DateTimeInterface $fechaAnulacion): \App\Entity\Pago
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAnulacion', [$fechaAnulacion]);

        return parent::setFechaAnulacion($fechaAnulacion);
    }

}
