<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AgendaObservacion extends \App\Entity\AgendaObservacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'agenda', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'usuarioRegistro', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'status', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'fechaRegistro', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'observacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'agenda', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'usuarioRegistro', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'status', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'fechaRegistro', '' . "\0" . 'App\\Entity\\AgendaObservacion' . "\0" . 'observacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AgendaObservacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAgenda(): ?\App\Entity\Agenda
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgenda', []);

        return parent::getAgenda();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgenda(?\App\Entity\Agenda $agenda): \App\Entity\AgendaObservacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgenda', [$agenda]);

        return parent::setAgenda($agenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioRegistro(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioRegistro', []);

        return parent::getUsuarioRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioRegistro(?\App\Entity\Usuario $usuarioRegistro): \App\Entity\AgendaObservacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioRegistro', [$usuarioRegistro]);

        return parent::setUsuarioRegistro($usuarioRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?\App\Entity\AgendaStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?\App\Entity\AgendaStatus $status): \App\Entity\AgendaObservacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaRegistro(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaRegistro', []);

        return parent::getFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaRegistro(\DateTimeInterface $fechaRegistro): \App\Entity\AgendaObservacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaRegistro', [$fechaRegistro]);

        return parent::setFechaRegistro($fechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion(string $observacion): \App\Entity\AgendaObservacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

}
