<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cuota extends \App\Entity\Cuota implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'fechaPago', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'monto', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'pagado', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'anular', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'fechaAnulacion', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'usuarioAnulacion', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'contrato', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'pagoCuotas', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'isMulta', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'anexo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'fechaPago', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'monto', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'pagado', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'anular', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'fechaAnulacion', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'usuarioAnulacion', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'contrato', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'pagoCuotas', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'isMulta', '' . "\0" . 'App\\Entity\\Cuota' . "\0" . 'anexo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cuota $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero(int $numero): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPago(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPago', []);

        return parent::getFechaPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPago(\DateTimeInterface $fechaPago): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPago', [$fechaPago]);

        return parent::setFechaPago($fechaPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto(int $monto): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagado(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagado', []);

        return parent::getPagado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagado(?int $pagado): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagado', [$pagado]);

        return parent::setPagado($pagado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnular(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnular', []);

        return parent::getAnular();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnular(?bool $anular): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnular', [$anular]);

        return parent::setAnular($anular);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAnulacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAnulacion', []);

        return parent::getFechaAnulacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAnulacion(?\DateTimeInterface $fechaAnulacion): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAnulacion', [$fechaAnulacion]);

        return parent::setFechaAnulacion($fechaAnulacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioAnulacion(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioAnulacion', []);

        return parent::getUsuarioAnulacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioAnulacion(?\App\Entity\Usuario $usuarioAnulacion): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioAnulacion', [$usuarioAnulacion]);

        return parent::setUsuarioAnulacion($usuarioAnulacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrato(): ?\App\Entity\Contrato
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrato', []);

        return parent::getContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrato(?\App\Entity\Contrato $contrato): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrato', [$contrato]);

        return parent::setContrato($contrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoCuotas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoCuotas', []);

        return parent::getPagoCuotas();
    }

    /**
     * {@inheritDoc}
     */
    public function addPagoCuota(\App\Entity\PagoCuotas $pagoCuota): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPagoCuota', [$pagoCuota]);

        return parent::addPagoCuota($pagoCuota);
    }

    /**
     * {@inheritDoc}
     */
    public function removePagoCuota(\App\Entity\PagoCuotas $pagoCuota): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePagoCuota', [$pagoCuota]);

        return parent::removePagoCuota($pagoCuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMulta(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMulta', []);

        return parent::getIsMulta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMulta(?bool $isMulta): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMulta', [$isMulta]);

        return parent::setIsMulta($isMulta);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnexo(): ?\App\Entity\ContratoAnexo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnexo', []);

        return parent::getAnexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnexo(?\App\Entity\ContratoAnexo $anexo): \App\Entity\Cuota
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnexo', [$anexo]);

        return parent::setAnexo($anexo);
    }

}
