<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuarioNoDisponible extends \App\Entity\UsuarioNoDisponible implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'horaInicio', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'horaFin', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'fechaInicio', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'fechaFin', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'anio', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'mes', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'dia', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'concepto'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'horaInicio', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'horaFin', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'fechaInicio', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'fechaFin', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'anio', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'mes', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'dia', '' . "\0" . 'App\\Entity\\UsuarioNoDisponible' . "\0" . 'concepto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuarioNoDisponible $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $fecha): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraInicio(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraInicio', []);

        return parent::getHoraInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraInicio(\DateTimeInterface $horaInicio): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraInicio', [$horaInicio]);

        return parent::setHoraInicio($horaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFin', []);

        return parent::getHoraFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFin(\DateTimeInterface $horaFin): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFin', [$horaFin]);

        return parent::setHoraFin($horaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(?\App\Entity\Usuario $usuario): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', []);

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio(?\DateTimeInterface $fechaInicio): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', [$fechaInicio]);

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', []);

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin(?\DateTimeInterface $fechaFin): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', [$fechaFin]);

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnio(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnio', []);

        return parent::getAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnio(?int $anio): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnio', [$anio]);

        return parent::setAnio($anio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMes(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMes', []);

        return parent::getMes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMes(?int $mes): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMes', [$mes]);

        return parent::setMes($mes);
    }

    /**
     * {@inheritDoc}
     */
    public function getDia(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDia', []);

        return parent::getDia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDia(?int $dia): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDia', [$dia]);

        return parent::setDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function getConcepto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConcepto', []);

        return parent::getConcepto();
    }

    /**
     * {@inheritDoc}
     */
    public function setConcepto(string $concepto): \App\Entity\UsuarioNoDisponible
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConcepto', [$concepto]);

        return parent::setConcepto($concepto);
    }

}
