<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ContratoRol extends \App\Entity\ContratoRol implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'nombreRol', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'institucionAcreedora', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'juzgado', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'contrato', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'abogado'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'nombreRol', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'institucionAcreedora', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'juzgado', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'contrato', '' . "\0" . 'App\\Entity\\ContratoRol' . "\0" . 'abogado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ContratoRol $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreRol(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreRol', []);

        return parent::getNombreRol();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreRol(string $nombreRol): \App\Entity\ContratoRol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreRol', [$nombreRol]);

        return parent::setNombreRol($nombreRol);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstitucionAcreedora(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstitucionAcreedora', []);

        return parent::getInstitucionAcreedora();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstitucionAcreedora(string $institucionAcreedora): \App\Entity\ContratoRol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstitucionAcreedora', [$institucionAcreedora]);

        return parent::setInstitucionAcreedora($institucionAcreedora);
    }

    /**
     * {@inheritDoc}
     */
    public function getJuzgado(): ?\App\Entity\Juzgado
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJuzgado', []);

        return parent::getJuzgado();
    }

    /**
     * {@inheritDoc}
     */
    public function setJuzgado(?\App\Entity\Juzgado $juzgado): \App\Entity\ContratoRol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJuzgado', [$juzgado]);

        return parent::setJuzgado($juzgado);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrato(): ?\App\Entity\Contrato
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrato', []);

        return parent::getContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrato(?\App\Entity\Contrato $contrato): \App\Entity\ContratoRol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrato', [$contrato]);

        return parent::setContrato($contrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbogado(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbogado', []);

        return parent::getAbogado();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbogado(?\App\Entity\Usuario $abogado): \App\Entity\ContratoRol
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbogado', [$abogado]);

        return parent::setAbogado($abogado);
    }

}
